FROM adoptopenjdk/openjdk8-openj9:latest

ENV MAVEN_VERSION 3.6.3

RUN mkdir -p /usr/share/maven \
  && curl -fsSL https://mirrors.tuna.tsinghua.edu.cn/apache/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz \
    | tar -xzC /usr/share/maven --strip-components=1 \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_HOME /usr/share/maven

VOLUME /root/.m2

RUN \
  sed -i -E -e 's/(archive|security)\.ubuntu\.com/mirrors\.tuna\.tsinghua\.edu\.cn/g' /etc/apt/sources.list && \
  apt-get update && \
  apt-get install -y build-essential cmake zlib1g-dev pkg-config libssl-dev libzstd-dev libsnappy-dev libbz2-dev libfuse-dev libisal-dev libsasl2-dev && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ARG HADOOP_VERSION=
ARG PROTOBUF_VERSION=

ADD \
  hadoop-${HADOOP_VERSION}-src.tar.gz \
  protobuf-${PROTOBUF_VERSION}.tar.gz \
  /tmp/

RUN \
  cd /tmp/protobuf-${PROTOBUF_VERSION} && \
  ./configure && \
  make -j$(nproc) && make install

ENV LD_LIBRARY_PATH /usr/local/lib
ENV export LD_RUN_PATH /usr/local/lib

# build native libs
ADD \
  settings.xml \
  /root/.m2/
ADD \
  repository \
  /root/.m2/repository/
ADD \
  hdfs-native-client.patch \
  /tmp/

RUN \
  cd /tmp/hadoop-${HADOOP_VERSION}-src && \
  patch -p1 < ../hdfs-native-client.patch && \
  mvn package -Pdist,native -DskipTests -Dtar -Drequire.openssl -Drequire.zstd -Drequire.snappy -Drequire.isal -Djava.net.preferIPv4Stack=true

# tar to stdout
CMD tar -cv -C /tmp/hadoop-${HADOOP_VERSION}-src/hadoop-dist/target/hadoop-${HADOOP_VERSION}/lib/native/ .
